force-app/main/default/objects/Financial_Advices__c/Financial_Advices__c.object-meta.xml
<CustomObject>
    <label>Financial Advice</label>
    <nameField>
        <label>Financial Advices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Advices__c/fields/Advice_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Advice_Date_Time__c</fullName>
    <label>Advice Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Financial_Advices__c/fields/Reccommendation__c.field-meta.xml
<CustomField>
    <fullName>Reccommendation__c</fullName>
    <label>Reccommendation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TaskController.cls
public with sharing class TaskController {
    @AuraEnabled(cacheable=true)
    public static List<Task> getAllTasks() {
         return [SELECT Id, Subject, Description, ActivityDate FROM Task WHERE Status != 'Completed' ORDER BY ActivityDate ASC];
    }
    
    @AuraEnabled(cacheable=true)
public static List<Financial_Advices__c> getUpcomingMeetings() {
    DateTime now = System.now();
    return [
        SELECT Id, Name, Advice_Date_Time__c, Reccommendation__c
        FROM Financial_Advices__c
        WHERE Advice_Date_Time__c > :now
        ORDER BY Advice_Date_Time__c ASC
    ];
}

}